title: Omar Al-Farajat # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Recent graduate from Concordia University. Bachelor of Computer Science in Computer Games.
  <br><br>
  Interested in game development and simulation. 
  <br><br>
  <a href="https://www.linkedin.com/in/omar-farajat/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-167556789-1 # your Google Analytics tracking ID here
